# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReciteWordsInitSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SettingDate', models.DateTimeField()),
                ('CountOfEveryDay', models.IntegerField()),
                ('VocabularyCategory', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReciteWordsRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecordingDate', models.DateTimeField()),
                ('IndexOfCET4', models.IntegerField()),
                ('IndexOfCET6', models.IntegerField()),
                ('IndexOfGRE', models.IntegerField()),
                ('IndexOfTOEFL', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRigisterInfo',
            fields=[
                ('NickName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Phone', models.CharField(max_length=11)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VocabularyEN', models.CharField(max_length=50)),
                ('VocabularyCH', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VocabularyEN', models.CharField(max_length=50)),
                ('NoteContent', models.TextField()),
                ('IsShared', models.CharField(max_length=1)),
                ('CreateTime', models.DateTimeField()),
                ('NickName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelloWordsApp.UserRigisterInfo')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyRelatedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VocabularyEN', models.CharField(max_length=50)),
                ('ExampleSentences', models.TextField()),
                ('ExampleSentencesCH', models.TextField()),
                ('Synonym', models.CharField(max_length=50)),
                ('SynonymCH', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='recitewordsrecords',
            name='NickName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelloWordsApp.UserRigisterInfo'),
        ),
        migrations.AddField(
            model_name='recitewordsinitsettings',
            name='NickName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelloWordsApp.UserRigisterInfo'),
        ),
    ]
